// Auto-generated service bridge plugin: @(srv_type)
// Generated by: ros2 agnocast generate-bridge-plugins

#include "agnocast/agnocast.hpp"

#include "rclcpp/rclcpp.hpp"
#include "rclcpp/version.h"

#include <utility>

#include "@(header_path)"

extern "C" ServiceBridgeEntity create_r2a_service_bridge_@(snake_type_name)(
  rclcpp::Node::SharedPtr node, const std::string & service_name,
  const rclcpp::QoS & qos /*QoS for the target Agnocast service*/)
{
  using ServiceT = @(cpp_type);
  using AgnoClient = agnocast::BasicClient<ServiceT, agnocast::NoBridgeRequestPolicy>;

  auto srv_cb_group = node->create_callback_group(rclcpp::CallbackGroupType::Reentrant);
  auto client_cb_group = node->create_callback_group(rclcpp::CallbackGroupType::Reentrant);

  auto agno_client = std::make_shared<AgnoClient>(node.get(), service_name, qos, client_cb_group);

  auto ros_srv = node->create_service<ServiceT>(
    service_name,
    [agno_client](
      typename rclcpp::Service<ServiceT>::SharedPtr service_handle,
      std::shared_ptr<rmw_request_id_t> request_header,
      typename ServiceT::Request::SharedPtr ros_req) {
      auto agno_req = agno_client->borrow_loaned_request();
      *agno_req = *ros_req;

      agno_client->async_send_request(
        std::move(agno_req),
        [service_handle, request_header](typename agnocast::Client<ServiceT>::SharedFuture future) {
          auto agno_res = future.get();
          typename ServiceT::Response ros_res;
          ros_res = *agno_res;
          service_handle->send_response(*request_header, ros_res);
        });
    },
#if RCLCPP_VERSION_MAJOR >= 28
    qos, srv_cb_group);
#else
    qos.get_rmw_qos_profile(), srv_cb_group);
#endif

  return {ros_srv, srv_cb_group, client_cb_group};
}

extern "C" ServiceBridgeEntity create_a2r_service_bridge_@(snake_type_name)(
  rclcpp::Node::SharedPtr node, const std::string & service_name, const rclcpp::QoS & qos)
{
  using ServiceT = @(cpp_type);
  using AgnoService = agnocast::BasicService<ServiceT, agnocast::NoBridgeRequestPolicy>;

  auto srv_cb_group = node->create_callback_group(rclcpp::CallbackGroupType::Reentrant);
  auto client_cb_group = node->create_callback_group(rclcpp::CallbackGroupType::Reentrant);

  auto ros_client =
    node->create_client<ServiceT>(service_name, qos.get_rmw_qos_profile(), client_cb_group);

  auto agno_srv = std::make_shared<AgnoService>(
    node.get(), service_name,
    [ros_client](
      typename AgnoService::SharedPtr service_handle,
      agnocast::ipc_shared_ptr<typename ServiceT::Request> && agno_req) {
      auto ros_req = std::make_shared<typename ServiceT::Request>();
      *ros_req = *agno_req;

      ros_client->async_send_request(
        ros_req, [service_handle = std::move(service_handle), agno_req = std::move(agno_req)](
                   typename rclcpp::Client<ServiceT>::SharedFuture future) {
          auto ros_res = future.get();
          auto agno_res = service_handle->borrow_loaned_response(agno_req);
          *agno_res = *ros_res;
          // Resort to pointer copying because a mutable lambda can't be used here.
          auto agno_req_movable = agno_req;
          service_handle->send_response(std::move(agno_req_movable), std::move(agno_res));
        });
    },
    qos, srv_cb_group);

  return {agno_srv, srv_cb_group, client_cb_group};
}
