// Auto-generated pubsub bridge plugin: sensor_msgs/msg/Imu
// Generated by: ros2 agnocast generate-bridge-plugins

#include "agnocast/agnocast.hpp"

#include "rclcpp/rclcpp.hpp"

#include <utility>

#include "sensor_msgs/msg/imu.hpp"

extern "C" PerformancePubsubBridgeResult create_r2a_pubsub_bridge(
  rclcpp::Node::SharedPtr node,
  const std::string & topic_name,
  const rclcpp::QoS & sub_qos)
{
  using AgnoPub = agnocast::BasicPublisher<sensor_msgs::msg::Imu, agnocast::NoBridgeRequestPolicy>;

  auto agno_pub = std::make_shared<AgnoPub>(
    node.get(),
    topic_name,
    rclcpp::QoS(agnocast::DEFAULT_QOS_DEPTH).transient_local(),
    agnocast::PublisherOptions{},
    true);

  auto ros_cb_group = node->create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);

  rclcpp::SubscriptionOptions ros_opts;
  ros_opts.ignore_local_publications = true;
  ros_opts.callback_group = ros_cb_group;

  auto ros_sub = node->create_subscription<sensor_msgs::msg::Imu>(
    topic_name,
    sub_qos,
    [agno_pub](const sensor_msgs::msg::Imu::ConstSharedPtr msg) {
      auto loaned_msg = agno_pub->borrow_loaned_message();
      *loaned_msg = *msg;
      agno_pub->publish(std::move(loaned_msg));
    },
    ros_opts);

  return {ros_sub, ros_cb_group};
}

extern "C" PerformancePubsubBridgeResult create_a2r_pubsub_bridge(
  rclcpp::Node::SharedPtr node,
  const std::string & topic_name,
  const rclcpp::QoS & sub_qos)
{
  auto ros_pub = node->create_publisher<sensor_msgs::msg::Imu>(
    topic_name, rclcpp::QoS(agnocast::DEFAULT_QOS_DEPTH).reliable().transient_local());

  auto cb_group = node->create_callback_group(rclcpp::CallbackGroupType::MutuallyExclusive);

  auto agno_callback = [ros_pub](const agnocast::ipc_shared_ptr<sensor_msgs::msg::Imu> msg) {
    auto loaned_msg = ros_pub->borrow_loaned_message();
    if (loaned_msg.is_valid()) {
      loaned_msg.get() = *msg;
      ros_pub->publish(std::move(loaned_msg));
    } else {
      ros_pub->publish(*msg);
    }
  };

  agnocast::SubscriptionOptions sub_opts;
  sub_opts.ignore_local_publications = true;
  sub_opts.callback_group = cb_group;

  using AgnoSub = agnocast::BasicSubscription<sensor_msgs::msg::Imu, agnocast::NoBridgeRequestPolicy>;
  auto agno_sub = std::make_shared<AgnoSub>(
    node.get(),
    topic_name,
    sub_qos,
    agno_callback,
    sub_opts,
    true);

  return {agno_sub, cb_group};
}
